In [24]:
# step 1 - install pytorch
%pip install -q torch

Note: you may need to restart the kernel to use updated packages.


In [ ]:
# Step 3 - import pytorch
import torch

In [ ]:
# Step 2 - get device to run model on - this is the main difference from what Markus showed us
device = torch.accelerator.current_accelerator().type if torch.accelerator.is_available() else "cpu"
print(f"Using {device} device")

Using mps device


In [ ]:
# Step 4 - define a simply neural network model
class OneLayerNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer = nn.Linear(8, 1)

    def forward(self, x):
        output = self.layer(x)
        return output

In [26]:
# Step 5 - instantiate mode, and create a suitable input tensor
input = torch.Tensor([1]*8)
neural_network = OneLayerNN()

In [27]:
input

tensor([1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
input.shape

torch.Size([8])

In [30]:
# You can see the weights here! If you recreate the tensor, the weights will change! This is because initialization is somewhat random!
list(neural_network.layer.named_parameters())

[('weight',
  Parameter containing:
  tensor([[ 0.3253, -0.0979,  0.1335,  0.1784,  0.0217, -0.3505,  0.1686, -0.2802]],
         requires_grad=True)),
 ('bias',
  Parameter containing:
  tensor([-0.0132], requires_grad=True))]

In [32]:
# Step 6 - apply the network to your input tensor
# Note that this is running on your CPU!!!
neural_network(input)

tensor([0.0858], grad_fn=<ViewBackward0>)

In [36]:
# Step 7 - try running it with apple mps acceleration
neural_network.to(device) # Send NN to mps
input = input.to(device) # Send input to mps
output = neural_network(input)
output.device # Note that the output is on the mps device too

device(type='mps', index=0)